In [4]:
import pandas as pd
import numpy as np
import numpy as np
from sklearn.metrics import mean_absolute_error, r2_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV

df = pd.read_csv('data.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [5]:
df.head(6)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes

In [6]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [7]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [8]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.loc[df['TotalCharges'].isna(), 'TotalCharges'] = df['TotalCharges'].mean()

In [9]:
df.loc[df['tenure'] == 0, 'TotalCharges']

488     2283.300441
753     2283.300441
936     2283.300441
1082    2283.300441
1340    2283.300441
3331    2283.300441
3826    2283.300441
4380    2283.300441
5218    2283.300441
6670    2283.300441
6754    2283.300441
Name: TotalCharges, dtype: float64

In [10]:
df = pd.get_dummies(df, columns=['Contract','InternetService','MultipleLines','PaymentMethod'], dtype=int)

In [11]:
cols_to_encode = ['StreamingTV', 'StreamingMovies','OnlineSecurity','TechSupport','OnlineBackup','DeviceProtection']
mapping = {'Yes': 1, 'No': 0, 'No internet service': 0}
for col in cols_to_encode:
    df[col] = df[col].map(mapping)
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})
cols_to_encode = ['Dependents', 'PhoneService','Partner','PaperlessBilling']
mapping = {'Yes': 1, 'No': 0, 'No internet service': 0}
for col in cols_to_encode:
    df[col] = df[col].map(mapping)

df.drop(columns=['customerID','OnlineBackup','DeviceProtection',], inplace=True)
df.shape

(7043, 27)

In [12]:
df.nunique()

gender                                        2
SeniorCitizen                                 2
Partner                                       2
Dependents                                    2
tenure                                       73
PhoneService                                  2
OnlineSecurity                                2
TechSupport                                   2
StreamingTV                                   2
StreamingMovies                               2
PaperlessBilling                              2
MonthlyCharges                             1585
TotalCharges                               6531
Churn                                         2
Contract_Month-to-month                       2
Contract_One year                             2
Contract_Two year                             2
InternetService_DSL                           2
InternetService_Fiber optic                   2
InternetService_No                            2
MultipleLines_No                              2
MultipleLines_No phone service                2
MultipleLines_Yes                             2
PaymentMethod_Bank transfer (automatic)       2
PaymentMethod_Credit card (automatic)         2
PaymentMethod_Electronic check                2
PaymentMethod_Mailed check                    2
dtype: int64

In [13]:
df.info()
df.drop([])

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 27 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   gender                                   7043 non-null   int64
 1   SeniorCitizen                            7043 non-null   int64
 2   Partner                                  7043 non-null   int64
 3   Dependents                               7043 non-null   int64
 4   tenure                                   7043 non-null   int64
 5   PhoneService                             7043 non-null   int64
 6   OnlineSecurity                           7043 non-null   int64
 7   TechSupport                              7043 non-null   int64
 8   StreamingTV                              7043 non-null   int64
 9   StreamingMovies                          7043 non-null   int64
 10  PaperlessBilling                         7043 non-null   int64
 11  MonthlyCharges                           7043 non-null   float64
 12  TotalCharges                             7043 non-null   float64
 13  Churn                                    7043 non-null   int64
 14  Contract_Month-to-month                  7043 non-null   int64
 15  Contract_One year                        7043 non-null   int64
 16  Contract_Two year                        7043 non-null   int64
 17  InternetService_DSL                      7043 non-null   int64
 18  InternetService_Fiber optic              7043 non-null   int64
 19  InternetService_No                       7043 non-null   int64
 20  MultipleLines_No                         7043 non-null   int64
 21  MultipleLines_No phone service           7043 non-null   int64
 22  MultipleLines_Yes                        7043 non-null   int64
 23  PaymentMethod_Bank transfer (automatic)  7043 non-null   int64
 24  PaymentMethod_Credit card (automatic)    7043 non-null   int64
 25  PaymentMethod_Electronic check           7043 non-null   int64
 26  PaymentMethod_Mailed check               7043 non-null   int64
dtypes: float64(2), int64(25)
memory usage: 1.5 MB

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,TechSupport,StreamingTV,StreamingMovies,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
1,1,0,0,0,34,1,1,0,0,0,...,1,0,0,1,0,0,0,0,0,1
2,1,0,0,0,2,1,1,0,0,0,...,1,0,0,1,0,0,0,0,0,1
3,1,0,0,0,45,0,1,1,0,0,...,1,0,0,0,1,0,1,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,1,1,1,...,1,0,0,0,0,1,0,0,0,1
7039,0,0,1,1,72,1,0,0,1,1,...,0,1,0,0,0,1,0,1,0,0
7040,0,0,1,1,11,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7041,1,1,1,0,4,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
7042,1,0,0,0,66,1,1,1,1,1,...,0,1,0,1,0,0,1,0,0,0

In [ ]:
y = df['Churn']
X = df.drop('Churn', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)
model = RandomForestClassifier(n_estimators=100,max_depth=10,class_weight='balanced',random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, None],
    'class_weight': ['balanced', None]  
}
grid_search = GridSearchCV(RandomForestClassifier(random_state=42), param_grid=params, cv=5, scoring='recall')
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'class_weight': ['balanced', None],
                         'max_depth': [10, 20, None],
                         'n_estimators': [100, 200, 300]},
             scoring='recall')

In [15]:
print(accuracy_score(y_test, y_pred))
features = pd.DataFrame({
    'feature': X.columns,
    'importance': model.feature_importances_
})
print(features.sort_values(by='importance', ascending=False))
print(model.feature_importances_)

0.7601135557132718
                                    feature  importance
13                  Contract_Month-to-month    0.143617
4                                    tenure    0.143582
12                             TotalCharges    0.131526
11                           MonthlyCharges    0.121081
15                        Contract_Two year    0.077851
17              InternetService_Fiber optic    0.062346
24           PaymentMethod_Electronic check    0.040034
18                       InternetService_No    0.033142
14                        Contract_One year    0.026451
10                         PaperlessBilling    0.023909
6                            OnlineSecurity    0.022642
16                      InternetService_DSL    0.020509
7                               TechSupport    0.016412
0                                    gender    0.015104
9                           StreamingMovies    0.014236
2                                   Partner    0.013833
3                                Dependents    0.013745
8                               StreamingTV    0.013209
1                             SeniorCitizen    0.011001
25               PaymentMethod_Mailed check    0.010014
22  PaymentMethod_Bank transfer (automatic)    0.009398
19                         MultipleLines_No    0.009392
23    PaymentMethod_Credit card (automatic)    0.009218
21                        MultipleLines_Yes    0.009216
5                              PhoneService    0.004648
20           MultipleLines_No phone service    0.003884
[0.01510372 0.01100118 0.01383304 0.01374469 0.14358181 0.00464784
 0.02264159 0.01641201 0.01320932 0.01423625 0.02390915 0.12108079
 0.13152552 0.14361704 0.02645094 0.07785108 0.02050865 0.06234598
 0.03314227 0.00939212 0.00388399 0.00921606 0.00939795 0.00921844
 0.04003408 0.01001448]

In [16]:
y_pred = model.predict(X_test)
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.90      0.76      0.82      1035\n           1       0.53      0.77      0.63       374\n\n    accuracy                           0.76      1409\n   macro avg       0.72      0.76      0.73      1409\nweighted avg       0.80      0.76      0.77      1409\n'

In [19]:
zx = model.predict_proba(X_test)
zx

array([[0.98006262, 0.01993738],
       [0.09103485, 0.90896515],
       [0.88642017, 0.11357983],
       ...,
       [0.77531723, 0.22468277],
       [0.90515035, 0.09484965],
       [0.95917699, 0.04082301]], shape=(1409, 2))